### ISSUE TITLE
Virtual.set /sensor not longer provided by virtual integration

### ISSUE THREAD

**Issue by Wiebrenk** [twrecked/hass-virtual#149]
After updating HA core to 2025.1 the following is going on with my virtual sensor (switches are fine);

The virtual sensor is unavailable with the following message; 
"This entity is no longer being provided by the virtual integration. If the entity is no longer in use, delete it in settings"

This sensor is fed by node red with "virtual.set", which states states the following;
"Action virtual.set not found"

No logs in ha which i can link to the virtual sensors HACCS repository / integration other than 

Logger: homeassistant.helpers.template
Source: helpers/template.py:2758
First occurred: 10:10:56 (1 occurrences)
Last logged: 10:10:56

Template variable warning: 'dict object' has no attribute 'action' when rendering '{{ value_json.action }}'

**Comment by AndreKR** [comment]
It's the same for lights.

**Comment by Tony763** [comment]
Hi, what version of Virtual integration?

**Comment by Wiebrenk** [comment]
> Hi, what version of Virtual integration?


I am sitting on 0.8.0.1

**Comment by AndreKR** [comment]
Yes, me too, it's the latest stable.

**Comment by Tony763** [comment]
I would recomend you to try, latest beta. All latest changed to HA are incomporated there (lot of breaking changes / deprecations).

**Comment by AndreKR** [comment]
Last time I tried the beta it was a disaster. Half the settings were in the UI, the other half in YAML files, some stuff was migrated wrong and I had to roll back to a backup. Is it better now?

**Comment by Tony763** [comment]
I run it for almost a year, configuration is still done in yaml (separate file from configuratin.yaml). You just add integration in HA Integrations menu and point integration to yaml file in integration settings.

**Comment by twrecked** [comment]
@AndreKR sorry about the issue before, there were some bugs in the upgrade code. For the record, all the settings are in the yaml file, all the integration does is point at the yaml file.

You should try 0.9; it probably fixes the issue. You can also add this to your current config

```yaml
virtual:
  yaml_config: True
```

to keep the old behaviour and use your current configuration. See https://github.com/twrecked/hass-virtual#i-dont-want-the-new-behaviour

If it doesn't fix your issue attach some debug, I'll take a look.

**Comment by CAT1210** [comment]
Just adding "yaml_config: True" didn't work for me. Sensors are still unavailable. What exactly do you need to see to troubleshoot? Here is a snap of my configuration.yaml:
![image](https://github.com/user-attachments/assets/c940c20b-d4a6-4d47-94f8-df7dd04fdfbe)
Developer tools also shows this configuration warning (after change to config and after reboot of the system):
![image](https://github.com/user-attachments/assets/f7b45d3a-1d87-412b-969a-746a313c4ff6)
Happy to provide anything else you need. Rolling Core back for now since the sensors are vital to home environment.

**Comment by CAT1210** [comment]
Yeah....I had that same thought after I sent in my message....thought it was beta or add this line instead of beta and add this line. Sorry about that. Upgraded to beta, added line, all good. Thank you!

**Comment by Wiebrenk** [comment]
For me all the issues has been solved by switching to the beta version, and later to the final 0.9.1. 

Thanks for the support :)

**Comment by AndreKR** [comment]
So, I don't know what happened but I just updated Home Assistant again and my virtual lights still work even though I still use 0.8. 🤷
